
request_disk          = 10000000
executable            = jobs_ADD_Truncation_v2_2017_ADDMonoZ2017_MD_2_d_8/script.sh
arguments             = $(ProcId) $(jobid)
transfer_input_files  = ../condor_Run2_proc.py,../combineHLT_Run2.yaml,../keep_and_drop.txt,../Cert_271036-284044_13TeV_ReReco_07Aug2017_Collisions16_JSON.txt,../Cert_294927-306462_13TeV_EOY2017ReReco_Collisions17_JSON_v1.txt,../Cert_314472-325175_13TeV_17SeptEarlyReReco2018ABC_PromptEraD_Collisions18_JSON.txt,../haddnano.py
output                = $(ClusterId).$(ProcId).out
error                 = $(ClusterId).$(ProcId).err
log                   = $(ClusterId).$(ProcId).log
initialdir            = jobs_ADD_Truncation_v2_2017_ADDMonoZ2017_MD_2_d_8
transfer_output_files = ""
+JobFlavour           = "testmatch"

queue jobid from jobs_ADD_Truncation_v2_2017_ADDMonoZ2017_MD_2_d_8/inputfiles.dat
